worker_processes 1;
pid /tmp/nginx.pid;
error_log /dev/stderr warn;

events {
    worker_connections 128;
}

stream {
    proxy_connect_timeout 5s;
    proxy_timeout 180s;

    server {
        listen 29443;
        proxy_pass bitcoin:18443;
    }

    server {
        listen 27051;
        proxy_pass elements:7041;
    }

    server {
        listen 29081;
        proxy_pass lnd-alice:8080;
    }

    server {
        listen 29082;
        proxy_pass lnd-bob:8080;
    }

    server {
        listen 22009;
        proxy_pass lnd-alice:10009;
    }

    server {
        listen 22010;
        proxy_pass lnd-bob:10009;
    }
}
